name: 'Set up Backblaze B2 CLI'
description: 'Download and add the `b2` command to the PATH'
branding:
  color: 'red'
  icon: 'cloud'
runs:
  using: "composite"
  steps:
    - if: runner.os == 'Linux'
      run: |
        sudo wget -O /usr/bin/b2 'https://f000.backblazeb2.com/file/backblazefiles/b2/cli/linux/b2'
        sudo chmod +x /usr/bin/b2
    - if: runner.os == 'macOS'
      run: |
        sudo wget -O /usr/local/bin/b2 'https://f000.backblazeb2.com/file/backblazefiles/b2/cli/osx/b2'
        sudo chmod +x /usr/local/bin/b2
    - if: runner.os == 'Windows'
      run: |
        Invoke-WebRequest -OutFile C:\Windows\system32\b2.exe 'https://f000.backblazeb2.com/file/backblazefiles/b2/cli/windows/b2.exe'
